#ifndef __LIBSWITCH_VERSION__H_
#define __LIBSWITCH_VERSION__H_

#define MODULE_COMPONENT_ID "libswitch"
#define MODULE_VERSION_ID "0.0.0.0.1"
#define VERSION_ID	"DJCS "MODULE_COMPONENT_ID" "MODULE_VERSION_ID

#endif // #if __LIBSWITCH_VERSION__H_
